/**
 * corpus.js — Stock phrases for the indictment and the bench.
 *
 * Openers and closers frame the procedural prosecution. Remarks arrive with
 * the stamp. Each line is a complete thought, safe to drop into a paragraph.
 */

export const OPENERS = [
  'Your Honour, the facts are not in dispute.',
  'The prosecution will be brief, because the evidence is not complicated.',
  'Ladies and gentlemen of the jury, we have all been here before.',
  'Your Honour, I ask the court to note the defendant is not making eye contact.',
  'The State calls this exhibit what it is.',
  'Your Honour, this will not take long.',
  'The State has the receipt. That is, in the main, the case.',
  'Your Honour, the documentary evidence is the defendant\'s own thumb.',
  'The court has seen this merchant. The defendant has seen it more recently.',
  'Your Honour, we proceed on a timestamp and an amount. Both are unkind.',
  'The prosecution opens with the facts, which decline to be interesting.',
  'Your Honour, there is a confirmation email. The State considers that sufficient.',
  'The facts are numbered, dated, and already in evidence.',
  'Your Honour, the defendant completed checkout. The rest is commentary.',
  'The State alleges a purchase. The ledger is prepared to swear to it.',
  'Your Honour, we are not here to interpret. We are here to read a line item.',
  'The prosecution notes the hour, the merchant, and the absence of a second thought.',
  'Your Honour, this is a case about a button that was pressed.',
  'The State will not dramatise the evidence. The timestamp has done that.',
  'Your Honour, the defendant\'s bank has already taken a view.',
  'The prosecution invites the court to consider the amount, and then the time.',
  'Your Honour, no conspiracy is alleged. A cart was simply paid for.',
  'The State has prepared a brief. It fit on one page.',
  'Your Honour, the evidence arrived itemised. The merchant was thorough.',
  'The prosecution is ready. The defendant appears to have been ready somewhat earlier.',
];

export const CLOSERS = [
  'The prosecution rests, exhausted.',
  'We ask the court to convict, and to do so briskly.',
  'The State seeks the maximum penalty the defendant will actually comply with.',
  'The prosecution rests. The defendant may now explain themselves.',
  'That is the case for the State. It took very little effort to assemble.',
  'The State has nothing to add that the amount has not already said.',
  'We leave the exhibits where they are, which is in front of everyone.',
  'The prosecution sits. The facts do not.',
  'That concludes the case for the State. The rest is the defendant\'s problem.',
  'We ask the court to look at the timestamp once more, and then to rule.',
  'The State rests, having used fewer words than the merchant used in the confirmation email.',
  'The prosecution has finished. The spending, regrettably, had also finished.',
  'We commend the evidence to the court. It requires no translation.',
  'The State will not summarise. The docket already has.',
  'That is all. The receipt was quite long enough.',
  'The prosecution rests on the documents, which refuse to be embarrassed.',
  'We ask for a verdict commensurate with the cart.',
  'The State yields the floor. The defendant had already used it, at the checkout.',
  'The prosecution has made its point. The bank made it first.',
  'We rest. The court may now hear why this was, apparently, different.',
  'The State concludes. The merchant has already been paid.',
  'That is the case. It is not a long case.',
  'The prosecution asks the court not to overthink what was not overthought at the time.',
  'We rest on the record. The record is a debit.',
  'The State has concluded. The receipt had concluded first.',
];

export const REMARKS_GUILTY = [
  'The court finds the defendant knew exactly what they were doing, and did it anyway.',
  'This was not a lapse. This was a decision, made with a thumb.',
  'The defendant will now watch the money leave a second time, in their imagination.',
  'The court finds fault, but recognises a human being under considerable pressure.',
  'Guilty, but the court has seen worse this week. In this same docket.',
  'The court has read the timestamp. The timestamp has read the defendant.',
  'Conviction follows. The purchase was not confused about its purpose.',
  'The court is not angry. The court is accurate.',
  'Guilty. The exhibits were, in the end, a receipt.',
  'The court finds that the defendant was present for the entire transaction.',
  'This was spending with a pulse. The pulse was not a defence.',
  'The court records a conviction and declines to be surprised.',
  'Guilty. The court notes the merchant was paid promptly, which is more than can be said for the defendant\'s judgment.',
  'The court has heard the plea. The court has also heard this plea before.',
  'A conviction is entered. The amount remains the amount.',
  'The court finds the facts as stated on the statement.',
  'Guilty, with the court\'s compliments to the timestamp, which did most of the work.',
  'The defendant may keep the item. The court will keep the record.',
  'The court is satisfied, in the unhappy sense.',
  'Conviction. The court has seen the confirmation email and considers the matter closed.',
  'The court finds that a saved card is not a mitigating circumstance.',
  'Guilty. The court will not be adding this to the folklore. It is already in the docket.',
  'The court finds the purchase was completed, and that this is the problem.',
  'A guilty verdict is recorded. The savings account may now be introduced to the concept of restitution.',
  'The court has reached a view. It is the same view as the bank\'s.',
];

export const REMARKS_ACQUIT = [
  'The State failed to meet its burden. Barely.',
  'The court finds this was, on balance, a reasonable thing for a person to do.',
  'There is no case here. Next.',
  'The court thanks the defendant for a rare moment of financial dignity.',
  'Not guilty. The court is as surprised as the prosecution.',
  'Case dismissed. The bench still recognises a necessity when it sees one.',
  'The court will not convict a person for remaining alive.',
  'Acquitted. The exhibits were present. They were also unimpressive.',
  'The State overreached. The amount did not.',
  'Dismissed. The court has larger defendants.',
  'Not guilty. The court declines to make a spectacle of a sensible purchase.',
  'The prosecution is thanked for its time, which this charge did not deserve.',
  'The court finds necessity, and is almost disappointed.',
  'Acquitted, with a look. Do not make the court regret it.',
  'There is nothing here that a reasonable person would not also have bought.',
  'Case dismissed. The docket is not a venue for the prosecution\'s hobbies.',
  'The court records an acquittal and returns the defendant to their own finances.',
  'Not guilty. The timestamp, for once, is not incriminating.',
  'The State has proved a purchase. It has not proved a crime.',
  'Dismissed with as little ceremony as the transaction itself.',
];
